services:
  - type: web
    name: calidad-tec
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 1 --timeout 120
    envVars:
      - key: DATABASE_URL
        value: postgresql://postgres:bZIqGZes2ZuNMXZ6@db.vpivzxkttjsgkpxyvpvp.supabase.co:5432/postgres
      - key: CLOUDINARY_CLOUD_NAME
        value: dgb8eri7
      - key: CLOUDINARY_UPLOAD_PRESET
        value: chiriqui_fotos
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: FLASK_ENV
        value: production
